#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPagesCustomApiAdapter.EarlyBounds
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MwO_PowerPagesActionType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Custom API", 0)]
		CustomApi = 407770000,
	}
}
#pragma warning restore CS1591
