#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPagesCustomApiAdapter.EarlyBounds
{
	
	
	/// <summary>
	/// Power Pages Component Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PowerPageComponentType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ad Placement", 21, "#0000ff")]
		AdPlacement = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Advanced Form", 17, "#0000ff")]
		AdvancedForm = 19,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Advanced Form Metadata", 19, "#0000ff")]
		AdvancedFormMetadata = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Advanced Form Step", 18, "#0000ff")]
		AdvancedFormStep = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Basic Form", 13, "#0000ff")]
		BasicForm = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Basic Form Metadata", 14, "#0000ff")]
		BasicFormMetadata = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bot Consumer", 22, "#0000ff")]
		BotConsumer = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cloud Flow", 28, "#0000ff")]
		CloudFlow = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Column Permission", 24, "#0000ff")]
		ColumnPermission = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Column Permission Profile", 23, "#0000ff")]
		ColumnPermissionProfile = 28,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Content Snippet", 6, "#0000ff")]
		ContentSnippet = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("List", 15, "#0000ff")]
		List = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Page Template", 5, "#0000ff")]
		PageTemplate = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Poll Placement", 20, "#0000ff")]
		PollPlacement = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Publishing State", 0, "#0000ff")]
		PublishingState = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Publishing State Transition Rule", 26, "#0000ff")]
		PublishingStateTransitionRule = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Redirect", 25, "#0000ff")]
		Redirect = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Shortcut", 27, "#0000ff")]
		Shortcut = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Site Marker", 12, "#0000ff")]
		SiteMarker = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Site Setting", 8, "#0000ff")]
		SiteSetting = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Table Permission", 16, "#0000ff")]
		TablePermission = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UX Component", 29, "#0000ff")]
		UxComponent = 34,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web File", 2, "#0000ff")]
		WebFile = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Link", 4, "#0000ff")]
		WebLink = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Link Set", 3, "#0000ff")]
		WebLinkSet = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Page", 1, "#0000ff")]
		WebPage = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Page Access Control Rule", 9, "#0000ff")]
		WebPageAccessControlRule = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Role", 10, "#0000ff")]
		WebRole = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Website Access", 11, "#0000ff")]
		WebsiteAccess = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Template", 7, "#0000ff")]
		WebTemplate = 8,
	}
}
#pragma warning restore CS1591
